# Generated by Django 4.1.4 on 2022-12-29 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=25)),
                ('Phone', models.BigIntegerField()),
                ('Role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], max_length=10)),
                ('Status', models.CharField(choices=[('0', 'INACTIVE'), ('1', 'ACTIVE')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_category_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='product_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_name', models.CharField(max_length=25)),
                ('Pro_image', models.ImageField(upload_to='photos')),
                ('Pro_description', models.TextField()),
                ('Pro_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='product_stock_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Updated_time', models.DateTimeField(auto_now=True)),
                ('Pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymobile.product_detail')),
            ],
        ),
        migrations.CreateModel(
            name='product_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Address', models.CharField(max_length=35)),
                ('Payment_status', models.CharField(max_length=30)),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.TimeField(auto_now=True)),
                ('L_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymobile.login')),
                ('Pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymobile.product_detail')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ratings', models.CharField(max_length=25)),
                ('Comment', models.CharField(max_length=25)),
                ('L_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymobile.login')),
            ],
        ),
        migrations.CreateModel(
            name='customer_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Dob', models.DateField()),
                ('Address', models.CharField(max_length=128)),
                ('Dp', models.ImageField(upload_to='photos')),
                ('Area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymobile.area')),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymobile.city')),
                ('L_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymobile.login')),
                ('State_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymobile.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='State_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymobile.state'),
        ),
        migrations.AddField(
            model_name='area',
            name='City_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymobile.city'),
        ),
        migrations.AddField(
            model_name='area',
            name='STATE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymobile.state'),
        ),
    ]
