# Generated by Django 4.1.5 on 2023-01-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymobile', '0004_alter_customer_detail_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_detail',
            name='Dp',
        ),
    ]
