# Generated by Django 4.1.5 on 2023-01-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymobile', '0008_remove_customer_detail_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='dp',
            field=models.ImageField(default='mydp.jpeg', upload_to='photos'),
        ),
    ]
