# Generated by Django 4.1.5 on 2023-01-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymobile', '0009_login_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='dp',
        ),
        migrations.AddField(
            model_name='customer_detail',
            name='dp',
            field=models.ImageField(default='mydp.jpeg', upload_to='photos'),
        ),
    ]
