# Generated by Django 4.1.5 on 2023-02-01 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymobile', '0010_remove_login_dp_customer_detail_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='Pro_Cat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mymobile.product_category'),
        ),
    ]
