# Generated by Django 4.1.5 on 2023-02-01 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymobile', '0012_remove_feedback_l_id_remove_feedback_ratings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_order',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='Pro_id',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='Time',
        ),
        migrations.AddField(
            model_name='product_order',
            name='Date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product_order',
            name='Total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('placed', 'PLACED')], max_length=50),
        ),
        migrations.CreateModel(
            name='product_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=300)),
                ('Date_time', models.DateTimeField(auto_now=True)),
                ('Price', models.IntegerField(default=100)),
                ('Quantity', models.IntegerField()),
                ('Final_price', models.IntegerField()),
                ('Order_id', models.IntegerField(default=0)),
                ('Order_status', models.IntegerField(default=0)),
                ('L_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mymobile.login')),
                ('Product_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mymobile.product_detail')),
            ],
        ),
    ]
