# Generated by Django 4.1.5 on 2023-02-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymobile', '0013_remove_product_order_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=50)),
                ('card_cvv', models.CharField(max_length=50)),
                ('exp_date', models.CharField(max_length=50)),
                ('card_balance', models.IntegerField(default=1000000)),
            ],
        ),
    ]
