# Generated by Django 4.1.7 on 2023-03-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymobile', '0015_feedback_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='Pro_name',
            field=models.CharField(max_length=100),
        ),
    ]
